/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkmastermind;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Ignacio
 */
public class VentanaMasterMind extends javax.swing.JFrame {

    String tipoObjeto = "Icono";
    int numObjetos = 6;
    int longitud = 3;
    int solucion[];
    int seleccionados[];
    int seleccion;
    
    ///
    JLabel  matrizUsuario[][];
    JLabel  matrizResult [][];
    JButton matrizSelect [];
    final int NUM_FILAS  = 10;
    final int ANCHO_BTN  = 36;
    final int ALTO_BTN   = 36;
    final int MARGEN_BTN = 5;
    final int ANCHO_RES  = 19;
    final int ALTO_RES   = 19;
    final int MARGEN_RES = 2;    
    
    public VentanaMasterMind() {
        initComponents();

        actualizaSelector();

        generaNuevaPartida();

        /////////////////////////////
        actualizaPaneles();
        
        
        generaSelector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPOpciones = new javax.swing.JPanel();
        jChkNivAuto = new javax.swing.JCheckBox();
        jCBLongitud = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCBDuplicados = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCBObjetos = new javax.swing.JComboBox();
        jBNuevaPartida = new javax.swing.JButton();
        jBColores = new javax.swing.JButton();
        jBIconos = new javax.swing.JButton();
        jBLetras = new javax.swing.JButton();
        jBNumeros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelSelector = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jPanelResult = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPOpciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jChkNivAuto.setSelected(true);
        jChkNivAuto.setText("Nivel Automático");
        jChkNivAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkNivAutoActionPerformed(evt);
            }
        });

        jCBLongitud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5", "6", "7", "8" }));
        jCBLongitud.setEnabled(false);
        jCBLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBLongitudActionPerformed(evt);
            }
        });

        jLabel2.setText("Longitud:");

        jCBDuplicados.setText("Permitir Duplicados");

        jLabel3.setText("Num. Objetos");

        jCBObjetos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "7", "8", "9", "10" }));
        jCBObjetos.setEnabled(false);
        jCBObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBObjetosActionPerformed(evt);
            }
        });

        jBNuevaPartida.setText("Nueva Partida");
        jBNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaPartidaActionPerformed(evt);
            }
        });

        jBColores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/color_1.png"))); // NOI18N
        jBColores.setBorder(null);
        jBColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBColoresActionPerformed(evt);
            }
        });

        jBIconos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cat_1.png"))); // NOI18N
        jBIconos.setBorder(null);
        jBIconos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIconosActionPerformed(evt);
            }
        });

        jBLetras.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jBLetras.setText("A");
        jBLetras.setBorder(null);
        jBLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLetrasActionPerformed(evt);
            }
        });

        jBNumeros.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jBNumeros.setText("0");
        jBNumeros.setBorder(null);
        jBNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNumerosActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione Tipo de Iconos:");

        javax.swing.GroupLayout jPOpcionesLayout = new javax.swing.GroupLayout(jPOpciones);
        jPOpciones.setLayout(jPOpcionesLayout);
        jPOpcionesLayout.setHorizontalGroup(
            jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOpcionesLayout.createSequentialGroup()
                        .addComponent(jBIconos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBColores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPOpcionesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBNuevaPartida))
                    .addGroup(jPOpcionesLayout.createSequentialGroup()
                        .addComponent(jChkNivAuto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBDuplicados))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPOpcionesLayout.setVerticalGroup(
            jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkNivAuto)
                    .addComponent(jCBDuplicados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jCBObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNuevaPartida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBColores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBIconos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        jPanelSelector.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelSelector.setPreferredSize(new java.awt.Dimension(48, 562));

        javax.swing.GroupLayout jPanelSelectorLayout = new javax.swing.GroupLayout(jPanelSelector);
        jPanelSelector.setLayout(jPanelSelectorLayout);
        jPanelSelectorLayout.setHorizontalGroup(
            jPanelSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanelSelectorLayout.setVerticalGroup(
            jPanelSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jPanelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelResultLayout = new javax.swing.GroupLayout(jPanelResult);
        jPanelResult.setLayout(jPanelResultLayout);
        jPanelResultLayout.setHorizontalGroup(
            jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        jPanelResultLayout.setVerticalGroup(
            jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                .addGap(0, 73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChkNivAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkNivAutoActionPerformed
        
        //Si ponemos el Nivel Automático Desactivamos el ComboBox
        if (jChkNivAuto.isSelected()) {
            jCBLongitud.setEnabled(false);
            jCBObjetos.setEnabled(false);
        } else {
            jCBLongitud.setEnabled(true);
            jCBObjetos.setEnabled(true);
        }
    }//GEN-LAST:event_jChkNivAutoActionPerformed


    
    
    private void actualizaSelector(){
        
        //Obtenemos el Numero de Objetos Seleccionados
        numObjetos = Integer.valueOf(jCBObjetos.getSelectedItem().toString());
        longitud   = Integer.valueOf(jCBLongitud.getSelectedItem().toString());
        
        //Inicializamos Matriz
        solucion = new int[longitud];
        
        //Si hay mas Filas que Objetos -> Permitimos Duplicados
        if (longitud > numObjetos) {
            jCBDuplicados.setSelected(true);
            jCBDuplicados.setEnabled(false);
        } else {
            jCBDuplicados.setEnabled(true);
        }
        //Reiniciamos los Botones
        generaSelector();
    }
            //jBSelector1.setIcon(getImageIcon("../Imagenes/color_2.png"));
    private ImageIcon getImageIcon(String nombreImagen){
        
        ImageIcon imagen = new ImageIcon(nombreImagen);
        return imagen;
    }
    
    private void jCBObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBObjetosActionPerformed
    }//GEN-LAST:event_jCBObjetosActionPerformed

    private void jBNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaPartidaActionPerformed
        
        //Generamos una Nueva Partida
        generaNuevaPartida();
        
        /////////////////////////////
        actualizaPaneles();        
    }//GEN-LAST:event_jBNuevaPartidaActionPerformed

    private void jCBLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBLongitudActionPerformed
    }//GEN-LAST:event_jCBLongitudActionPerformed
    private void jBColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBColoresActionPerformed

        //Establecemos los Colores como Tipo de Objeto
        tipoObjeto = "Color";
        
        generaSelector();
    }//GEN-LAST:event_jBColoresActionPerformed
    private void jBIconosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIconosActionPerformed

        //Establecemos los Iconos como Tipo de Objeto
        tipoObjeto = "Icono";
        
        generaSelector();
    }//GEN-LAST:event_jBIconosActionPerformed
    private void jBLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLetrasActionPerformed

        //Establecemos las Letras como Tipo de Objeto
        tipoObjeto = "Letra";
        
        generaSelector();
    }//GEN-LAST:event_jBLetrasActionPerformed
    private void jBNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNumerosActionPerformed

        //Establecemos los Numeros como Tipo de Objeto
        tipoObjeto = "Numero";
        
        generaSelector();
    }//GEN-LAST:event_jBNumerosActionPerformed
    private void generaSelector(){
        //Obtenemos el Numero de Columnas y Filas
        int numObjetos = Integer.valueOf(jCBObjetos.getSelectedItem().toString());

        int posBotonesX = MARGEN_BTN + 1;
        int posBotonesY = MARGEN_BTN + 1;
        
        //Inicializamos las Matrices
        matrizSelect = new JButton[numObjetos];
        
        //Inicializamos el Texto del Boton
        char letraBoton = '\0';
        if (tipoObjeto.equals("Letra"))
            letraBoton = 'A';
        else if (tipoObjeto.equals("Letra"))
            letraBoton = '0';
        
        //Generamos todos los Botones del Panel de Botones
        for (int posicion = 0; posicion < numObjetos; posicion++) {
            //Nuevo boton
            matrizSelect[posicion] = new JButton();
            matrizSelect[posicion].setSize(ANCHO_BTN, ALTO_BTN);
            matrizSelect[posicion].setLocation(posBotonesX, posBotonesY);
            
            switch(tipoObjeto){
                case "Icono":
                    matrizSelect[posicion].setIcon(new javax.swing.ImageIcon(getClass().getResource("../Imagenes/cat_" + (posicion + 1) + ".png")));
                    matrizSelect[posicion].setText("");
                    break;
                case "Color":
                    matrizSelect[posicion].setIcon(new javax.swing.ImageIcon(getClass().getResource("../Imagenes/color_" + (posicion + 1) + ".png")));
                    matrizSelect[posicion].setText("");
                    break;
                case "Letra":
                    matrizSelect[posicion].setText(""+letraBoton);
                    letraBoton++;
                    matrizSelect[posicion].setIcon(null);
                    break;
                case "Numero":
                    matrizSelect[posicion].setText(""+letraBoton);
                    letraBoton++;
                    matrizSelect[posicion].setIcon(null);
                    break;
            }
            //Añadimos los Botones a sus Paneles
            jPanelSelector.add(matrizSelect[posicion]);

            //Incrementamos X
            posBotonesY = posBotonesY + ANCHO_BTN + MARGEN_BTN;
        }
    }


    
    private void generaNuevaPartida()
    {
        //Generamos la Temperatura Aleatoria Inicial
        Random generadorNum = new Random();        
        int contador = 0;        
        seleccionados = new int [longitud];
        
        //Generamos los Numeros Aleatorios Definidos en 'numFilas'
        while (contador < longitud){
            //Generamos el Numero Aleatorio
            int numAleatorio = generadorNum.nextInt(numObjetos) + 1;
            
            //Si Estan Permitidos los Duplicados
            if (jCBDuplicados.isSelected()){     
                solucion[contador]=numAleatorio;
                contador++;
            }
            //Si no Estan Permitidos los Duplicados
            else if (!estaRepetido(numAleatorio)){  
                solucion[contador]=numAleatorio;
                contador++;
            }
        }
    }
    
    private boolean estaRepetido(int numAleatorio){
        int longSolucion = solucion.length;
        
        for (int x=0; x < longSolucion; x++){
            if (solucion[x] == numAleatorio)
                return true;
        }
        return false;
    }
    
    
    ////////////////////////////////////////
    private void actualizaPaneles(){
        
        //Obtenemos el Numero de Columnas y Filas
        int numCol = Integer.valueOf(jCBObjetos.getSelectedItem().toString());
        
        //Inicializamos el Panel de los Botones
        inicializaPanelBotones(numCol);
        
        //Inicializamos el Panel del Resultado
        inicializaPanelResultado(numCol);
        
        //Inicializamos el Panel Superior
        inicializaPanelSuperior();
    }
    private void inicializaPanelBotones(int numCol){
        //Limpiamos el Panel
        jPanelBotones.removeAll();
        
        //Añadimos los Botones al Panel de Botones
        generaBotones();
        
        //Cambiamos el Tamaño del Panel de Botones
        resizePanelBotones(numCol); 
    }
    //Cambiamos el Tamaño del Panel de Botones
    private void resizePanelBotones(int numCol){
        //Establecemos el Tamaño del Panel Botones
        int anchoPanel = (MARGEN_BTN + 2) + ((ANCHO_BTN + MARGEN_BTN) * numCol);
        int altoPanel  = (MARGEN_BTN + 2) + ((ALTO_BTN  + MARGEN_BTN) * NUM_FILAS);
        System.out.println("Tamaño Panel Botones - Ancho: " + anchoPanel + " - Alto: " + altoPanel);
        jPanelBotones.setSize(anchoPanel, altoPanel);
    }

    private void inicializaPanelResultado(int numCol){
        //Limpiamos el Panel
        jPanelResult.removeAll();
        
        //Reposicionamos el Panel Resultado
        posicionaPanelResultado();
        
        //Cambiamos el Tamaño del Panel Resultado
        resizePanelResultado(numCol);
        
        //Añadimos los label al Panel de Resultado
        generaLabel();
    }
    //Reposiciona el Panel del Resultado
    private void posicionaPanelResultado(){
        int posPanResX = jPanelBotones.getX() + jPanelBotones.getWidth() + MARGEN_BTN;
        jPanelResult.setLocation(posPanResX, jPanelResult.getY());
    }
    //Cambiamos el Tamaño del Panel Resultado
    private void resizePanelResultado(int numCol){
        int columRes = (numCol + 1) / 2;        
    
        //Establecemos el Tamaño del Panel Resultado
        int anchoPanel = (MARGEN_BTN * 2) + ((ANCHO_RES + MARGEN_RES) * columRes);
        int altoPanel  = (MARGEN_BTN + 2) + ((ALTO_BTN  + MARGEN_BTN) * NUM_FILAS);
        System.out.println("Tamaño Panel Resultado - Ancho: " + anchoPanel + " - Alto: " + altoPanel);
        jPanelResult.setSize(anchoPanel, altoPanel);
    }

    private void inicializaPanelSuperior(){        
        //Cambiamos el Tamaño del Panel Superior
        resizePanelSuperior();
    }
    //Cambiamos el Tamaño del Panel Superior
    private void resizePanelSuperior(){
        
        //Establecemos el Tamaño del Panel Superior
        int anchoPanel = jPanelResult.getX() + jPanelResult.getWidth()  + MARGEN_BTN;
        int altoPanel  = jPanelResult.getY() + jPanelResult.getHeight() + MARGEN_BTN;
        System.out.println("Tamaño Panel Superior - Ancho: " + anchoPanel + " - Alto: " + altoPanel);
        jPanelSelector.setSize(anchoPanel, altoPanel);
    } 


    
    
    private void generaBotones(){
        
        //Obtenemos el Numero de Columnas y Filas
        int numColumnas = Integer.valueOf(jCBObjetos.getSelectedItem().toString());
        
        int posBotonesX = MARGEN_BTN + 1;
        int posBotonesY = MARGEN_BTN + 1;

        //Inicializamos las Matrices
        matrizUsuario = new JLabel[NUM_FILAS][numColumnas];
        
        //Generamos todos los Botones del Panel de Botones
        for (int filas = 0; filas < NUM_FILAS; filas++) {
            for (int colum = 0; colum < numColumnas; colum++) {
                //Nuevo boton
                matrizUsuario[filas][colum] = new JLabel();
                matrizUsuario[filas][colum].setSize(ANCHO_BTN, ALTO_BTN);
                matrizUsuario[filas][colum].setLocation(posBotonesX, posBotonesY);
                matrizUsuario[filas][colum].setIcon(new javax.swing.ImageIcon(getClass().getResource("../Imagenes/Question.png")));
                
                //Añadimos los Botones a sus Paneles
                jPanelBotones.add(matrizUsuario[filas][colum]);

                //Incrementamos X
                posBotonesX = posBotonesX + ANCHO_BTN + MARGEN_BTN;
            }
            //Inicializamos Variables
            posBotonesX = MARGEN_BTN + 1;

            //Incrementamos Y
            posBotonesY = posBotonesY + ALTO_BTN + MARGEN_BTN;
        }
     }
    
    private void generaLabel(){
        
        //Obtenemos el Numero de Columnas y Filas
        int numColumnas = Integer.valueOf(jCBObjetos.getSelectedItem().toString());
        int columRes    = (numColumnas + 1) / 2;
        
        int posResultX  = MARGEN_BTN + 1;
        int posResultY  = MARGEN_BTN + 1;

        //Inicializamos las Matrices
        matrizResult  = new JLabel[NUM_FILAS][numColumnas];
        
        //Generamos todos los Label del Resultado
        for (int filas = 0; filas < NUM_FILAS; filas++) {
            for (int colum = 0; colum < numColumnas; colum++) {
                //Nuevo Label
                matrizResult [filas][colum] = new JLabel();
                matrizResult [filas][colum].setSize(ANCHO_RES, ALTO_RES);
                matrizResult [filas][colum].setLocation(posResultX , posResultY);
                matrizResult [filas][colum].setIcon(new javax.swing.ImageIcon(getClass().getResource("../Imagenes/check_verde.png")));

                //Añadimos los Botones a sus Paneles
                jPanelResult.add(matrizResult[filas][colum]);

                //Si ha llegado a la Mitad
                if ((colum + 1) == columRes) {
                    //Reposicionamos la Posicion X al Inicio
                    posResultX = MARGEN_BTN + 1;
                    
                    //Bajamos un Nivel la Posicion Y
                    posResultY = posResultY + ALTO_RES + MARGEN_RES;
                } 
                else {
                    //Aumentamos distancia en la Posicion X
                    posResultX = posResultX + ANCHO_RES + MARGEN_RES;
                }
            }
            //Reposicionamos la Posicion X al Inicio
            posResultX  = MARGEN_BTN + 1;

            //Aumentamos distancia en la Posicion Y
            posResultY  = posResultY  + ALTO_RES + MARGEN_BTN;
        }
    }
    ////////////////////////////////////////

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMasterMind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBColores;
    private javax.swing.JButton jBIconos;
    private javax.swing.JButton jBLetras;
    private javax.swing.JButton jBNuevaPartida;
    private javax.swing.JButton jBNumeros;
    private javax.swing.JCheckBox jCBDuplicados;
    private javax.swing.JComboBox jCBLongitud;
    private javax.swing.JComboBox jCBObjetos;
    private javax.swing.JCheckBox jChkNivAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPOpciones;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelResult;
    private javax.swing.JPanel jPanelSelector;
    // End of variables declaration//GEN-END:variables
}
